spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sleuth:
     web:
        client:
            enabled: true
        sampler:
          probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://192.168.3.15:9411/ # 指定了 Zipkin 服务器的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
      appname: ${spring.application.name}
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2
#tomcat 配置
server:
  tomcat:
    #最大连接数
    max-connections: 1000
    #最大线程数
    max-threads: 200
    #最小空闲线程数
    min-spare-threads: 10
    #最大接受的请求队列
    accept-count: 10000

#使用httpclient 替代默认的URL连接方式，并配置线程池
feign:
   httpclient:
     enable: true
     max-connections: 200
     max-connections-per-route: 50
   #开启熔断
   hystrix:
      enabled: true
   #开启压缩
   compression:
      request:
         enabled: true # 开启请求压缩
      response:
         enabled: true # 开启响应压缩

hystrix:
   command:
      default:
        #command 执行策略配置
        execution:
          isolation:
            strategy: THREAD
            thread:
              timeoutInMilliseconds: 3000
              interruptOnTimeout: true
              interruptOnCancel: true
            #只对信号量的策略有效，配置并发数
            semaphore:
              maxConcurrentRequests: 1000
        #熔断配置策略
        fallback:
          isolation:
            semaphore:
              maxConcurrentRequests: 1000
        #断路器配置策略
        circuitBreaker:
          sleepWindowInMilliseconds: 5000
   #线程池配置
   threadpool:
      default:
          coreSize: 10
          maximumSize: 500
          #设置allowMaximumSizeToDivergeFromCoreSize值为true时，maximumSize才有作用
          allowMaximumSizeToDivergeFromCoreSize: true
          maxQueueSize: 1500
          queueSizeRejectionThreshold: 1000
#监控断点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 3000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    ServerListRefreshInterval: 1000

logging:
  config: classpath:logback.xml