spring:
  profiles:
    active: dev
  application:
    name: spring-register-server
server:
  port: 8761

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
     #关闭自我保护模式
     enable-self-preservation: false
     #读写缓存和读缓存同步间隔
     response-cache-update-interval-ms: 3000
     # 设置清理间隔,单位为毫秒,默认为0
     eviction-interval-timer-in-ms: 5000
     # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
     wait-time-in-ms-when-sync-empty: 6000
     # 集群之间相互更新节点信息的时间频率
     peer-eureka-nodes-update-interval-ms: 60000